/*
.JS FILE CAN BE WRITTEN TO SAVE AND USE SCRIPT LATER
SCRIPT TAG CAN BE USED TO LINK SCRIPT TO HTML OR INSERT A INLINE JS SCRIPT
CONSOLE IT DISPLAY A  TEXT INFO IN WINDOWS CONSOLE
THE SCRIPT MUST BE ADDED ON FOOTE FOR FASTER RENDERING
*/
console.log(10,10.10,true,false,null,num);
//, seperate each value on print with space
var num=10;
// var can be logged to know what the num have init
console.log(num);
